from typing import Dict, Any, Optional
from .base import BaseGenerator

# In futuro importeremo l'interfaccia Provider
# from mockgen.providers.base import BaseProvider

class SmartGenerator(BaseGenerator):
    """
    Generatore che utilizza un LLM per produrre dati semanticamente ricchi.
    Delega la chiamata effettiva a un Provider (Adapter Pattern).
    """

    def __init__(self, provider_name: str = "openai", api_key: str = None, seed: int = None):
        # Qui in futuro istanzieremo il provider corretto
        # self.provider = ProviderFactory.get(provider_name, api_key)
        self.provider_name = provider_name
        self.seed = seed

    def generate(self, schema: Dict[str, Any], context: Optional[str] = None) -> Any:
        """
        Costruisce il prompt e invoca l'LLM.
        """
        print(f"DEBUG: SmartGenerator invocato con provider {self.provider_name}")
        print(f"DEBUG: Context: {context}")
        
        # MOCK TEMPORANEO: Simula una risposta AI valida
        # Quando implementeremo i providers, qui ci sarà: return self.provider.generate(schema, context)
        
        return {
            "_ai_metadata": "Generated by Mock Smart Generator",
            "note": "Questo è un dato finto finché non colleghiamo OpenAI",
            "context_received": context
        }